== OX
*Author*: _Krzysztof Jodłowski_ +
*Version*: _0.3_

*Description*: Simple _tic-tac-toe_ game.

To run project you have to use:

* bash or other compatible unix shell
* jdk version 11+
* maven version 3.6.0+

To run project:

- without any custom input run _"standard"_ script
- project with automated input run _"auto"_ script
- run script from command line by typing *_./standard.sh_* or *_./auto.sh_*
- if you can't run a script execute command *_chmod 755 standard.sh_* (or *_chmod 755 auto.sh_*) and then run it as explained above
- when run _"auto"_ script new folder with name matching DATE_TIME name in automata/ is created, inside that folder you can see automated tests results:
* draw
* "O" wins by matching first column
* "O" wins by matching second column
* "O" wins by matching third column
* "O" wins by matching first row
* "O" wins by matching second row
* "O" wins by matching third row
* "O" wins by matching slant line
* "O" wins by matching reversed slant line
- also, when you run _"auto"_ script in DATE_TIME folder tou can find an error summary (_README_ file) of comparing reference file (folder _templates_) with actual results

